### ISSUE TITLE
ChatChannel is null on game end

### ISSUE THREAD

**Issue by itsaphel** [VoxelGamesLib/VoxelGamesLibv2#72]
```
[22:52:07 WARNING]: [VoxelGamesLib] Task #4 for VoxelGamesLib v2.0-SNAPSHOT generated an exception
java.lang.NullPointerException
	at me.minidigger.voxelgameslib.game.AbstractGame.end(AbstractGame.java:272)
	at me.minidigger.voxelgameslib.game.AbstractGame.endGame(AbstractGame.java:255)
	at me.minidigger.voxelgameslib.game.AbstractGame.abortGame(AbstractGame.java:284)
	at me.minidigger.voxelgameslib.game.AbstractGame.endPhase(AbstractGame.java:225)
	at me.minidigger.voxelgameslib.phase.TimedPhase.tick(TimedPhase.java:72)
	at me.minidigger.voxelgameslib.game.AbstractGame.tick(AbstractGame.java:210)
	at java.util.ArrayList.forEach(ArrayList.java:1249)
	at me.minidigger.voxelgameslib.tick.TickHandler.tick(TickHandler.java:41)
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:71)
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:353)
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:738)
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:405)
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:678)
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:576)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by electronicboy** [comment]
STOP BREAKING STUFF, DUH

**Comment by LordRobust** [comment]
it broke itself :( wasn't me

**Comment by itsaphel** [comment]
wow, stupid commit closed it. i said "might fix" not "fixed" u dum dum
